[workspace]
resolver = "3"
members = [
    "crates/wire",
    "crates/transport",
    "crates/transport-capnp",
    "crates/transport-socks5h",
    "crates/transport-arti",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.lints.rust]
missing_docs = "warn"
rust_2018_idioms = "warn"
missing_debug_implementations = "warn"
